version: "3.8"

services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nyrkio/${ENV}/backend:${IMAGE_TAG}
    build: backend
    env_file:
      - .env.backend
    environment:
      - API_PORT=8000
    ports:
      - "8000:8000"
    hostname: api.nyrkio.local
  nginx:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nyrkio/${ENV}/nginx:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - SSL_DOMAIN
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - certbot
    volumes:
      - ./certbot/run/conf:/etc/nginx/ssl:ro
      - ./certbot/run/www:/var/www/certbot:ro
    restart: always
  certbot:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nyrkio/${ENV}/certbot:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./certbot/Dockerfile
    env_file:
      - .env.backend
    volumes:
      - ./certbot/run/conf/:/etc/letsencrypt/:rw
      - ./certbot/run/www/:/var/www/certbot/:rw
