version: "3.8"

services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nyrkio/${ENV}/backend:${IMAGE_TAG}
    build: backend
    env_file:
      - .env.backend
    environment:
      - API_PORT=8000
    ports:
      - "8000:8000"
    hostname: api.nyrkio.local
  nginx:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nyrkio/${ENV}/nginx:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - certbot
    volumes:
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: always
  certbot:
    env_file:
      - .env.backend
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@nyrk.io --agree-tos --no-eff-email -d nyrk.io -d nyrkio.com
