name: Docker Images (Prod)
on:
  push:
    branches: [main]

jobs:
  docker-images:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: eu-north-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ENV: prod
        run: |
          # Build a docker container and push it to ECR
          echo "${{ secrets.NYRKIO_ENV_PROD }}" > .env.backend
          # Unfortunately docker compose doesn't take a -t flag, so this is a
          # two-step process.
          docker compose -f docker-compose.yml build
          docker tag nyrkio-nginx:latest $ECR_REGISTRY/nyrkio/prod/nginx:$IMAGE_TAG
          docker tag nyrkio-backend:latest $ECR_REGISTRY/nyrkio/prod/backend:$IMAGE_TAG
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/nyrkio/prod/nginx:$IMAGE_TAG
          docker push $ECR_REGISTRY/nyrkio/prod/backend:$IMAGE_TAG
          echo "image=$ECR_REGISTRY:$IMAGE_TAG" >> $GITHUB_OUTPUT
